default['nginx-naxsi']['backend_server'] = "localhost:8080"
default['nginx-naxsi']['nginx_cache_dir'] = "/var/cache/nginx"
default['nginx-naxsi']['nginx_url'] = "http://nginx.org/download/nginx-1.9.9.tar.gz"
default['nginx-naxsi']['naxsi_url'] = "https://github.com/nbs-system/naxsi/archive/master.zip"
default['nginx-naxsi']['nginx_tar'] = "nginx-1.9.9.tar.gz"
default['nginx-naxsi']['naxsi_zip'] = "naxsi-master.zip"
default['nginx-naxsi']['hostname'] = "localhost"
